# Generated by Django 5.2.3 on 2025-11-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_stickynote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StickyNote',
        ),
    ]
